HamiltonianType = "Wannier90" # OpenMX, OpenMXWannier, Wannier90
spintype = "co_spin" #Set Spin type, para, co_spin, nc_spin
result_file = ["wannier90","wannier90"]
atom12 = [[1,1],[1,2]]

[wannier_optional]
# atom position info dose not exists at OpenMX wannier
# cell vector information read from wannier.win
atomnum = 2
atompos = [
            [0.0000000000000000,    0.0000000000000000,    0.0000000000000000],
            [0.5000000000000000,    0.5000000000000000,    0.5000000000000000]
           ]  # Atom 12 position x,y,z (fractional)

atoms_orbitals_list = [
                            [1], # Atom 1 orbitals
                            [2]  # Atom 2 orbitals
                      ]


[KaiEDJ]
Calculation_mode = "Spinwave" # DMFT, DMFT+MFT, Spinwave are possible.
SelfE_file = "SelfE"
chem_int    = 3.0

DMFT_loop_N = 50

KgridNum = [10,10,10]
RgridNum = [10,10,10]
Solver_green_Cut = 10

beta    = 128
NImFreq = 512

# Temperature   = 90.66035161070313  # kelvin
# iWgridCut     = 25.1327  # It's recommended to set a value larger than 5 times of Solver_green_Cut

mpi_prefix = ""
Corr_atom_Ind = [1,2]
Corr_orbital_Ind = [ [1],[2] ] # orbital order = wannier orbital order
Corr_atom_equiv = [1,2] # start from 1, minus sign means AFM, max(Corr_atom_equiv) = # of impurity problems

basis_transform = "false"
consider_degeneracy = false


EDMFTF_MonteCar_step = 5000000
EDMFTF_warmup_step = 500000
EDMFTF_GlobalFlip = 500000
EDMFTF_tsample = 30
EDMFTF_nom = 100
compute_EF = true



DMFT_Spin_type = 2 # 1: paramagnetic, 2 : spin-polarized

smth_step = 0
Mix_selfE  = 0 # The portion of Old selfenergy in the mixing
init_bias = 0.5

DMFT_solver = "ED"  # ED, ComCTQMC, EDMFTF_ctqmc are possible
nbath   = 10

# imp_dc_type = "FLL-DFT"
imp1_U = 6.0
imp1_J = 0
imp1_dc = 0.0
imp1_int_parameterisation = "slater-kanamori"
imp1_int_type = "full"
imp1_block = [[1]]

imp2_U = 6.0
imp2_J = 0
imp2_dc = 0.0
imp2_int_parameterisation = "slater-kanamori"
imp2_int_type = "full"
imp2_block = [[1]]
