rm BathParams_out_imp1.dat
rm BathParams_out_imp2.dat
rm DFT_CorrNele.dat
rm ECorrOrb
rm Nele.dat
rm SelfE_1.dat
rm SelfE_2.dat
rm bath_energy.dat
rm bath_hyb.dat
rm bath_info.dat
rm data
rm log
rm output_dmft.png
rm status.txt
rm status_imp1.txt
rm status_imp2.txt
rm status_latt.txt
rm transform_Mat.dat
